######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 19 12:38:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lgmpxx
QMAKE_CXXFLAGS += -Werror -g3

# Input
HEADERS += edge.h graph.h kruskal.h vertex.h
SOURCES += edge.cpp graph.cpp kruskal.cpp main.cpp vertex.cpp
